# Site settings
title: Blog of Tech@Yunlaiwu.com
header-img: img/home-bg.jpg
email: fanzhongkai@yunlaiwu.com
copyright_name: yunlaiwu
description: "Tech Team of Yunlaiwu.com!"
baseurl: "/blog"
url: "http://yunlaiwu.github.io"
email_username:  fanzhongkai@yunlaiwu.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
